### ISSUE TITLE
Failed to load a ide-kotlin package grammar

### ISSUE THREAD

**Issue by kidanekal** [fwcd/atom-ide-kotlin#1]
[Enter steps to reproduce:]

1.  Atom is failing to load ide-kotlin pacage, below is the error

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.14.6
**Thrown From**: [ide-kotlin](https://github.com/fwcd/atom-ide-kotlin) package 0.5.0

### Stack Trace

Failed to load a ide-kotlin package grammar

```
At The module '/Users/efeasf/.atom/packages/ide-kotlin/node_modules/tree-sitter-kotlin/build/Release/tree_sitter_kotlin_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 69. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`). in /Users/efeasf/.atom/packages/ide-kotlin/grammars/tree-sitter-kotlin.cson

Error: The module '/Users/efeasf/.atom/packages/ide-kotlin/node_modules/tree-sitter-kotlin/build/Release/tree_sitter_kotlin_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 69. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/ide-kotlin/node_modules/tree-sitter-kotlin/index.js:2:20)
    at /packages/ide-kotlin/node_modules/tree-sitter-kotlin/index.js:15:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:688212)
    at new TreeSitterGrammar (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3131248)
    at GrammarRegistry.createGrammar (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:360047)
    at l.readFile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:359888)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:581849
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
  at /packages/ide-kotlin/grammars/tree-sitter-kotlin.cson:1:1
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-java 1.2.7 
busy-signal 2.0.1 
go-plus 5.8.6 
ide-java 0.8.3 
ide-kotlin 0.5.0 
intentions 1.1.5 
language-docker 1.1.8 
language-kotlin 0.5.0 
language-terraform 0.8.1 
linter 2.3.1 
linter-kotlin 0.6.0 
linter-terraform-syntax 1.2.4 
linter-ui-default 1.7.1 
pretty-json 2.0.3 
terraform-fmt 0.3.0 
```

**Comment by fwcd** [comment]
Your Electron runtime's Node version most likely does not match the Node version used to build the package. This [apparently happens sometimes when updating Atom](https://github.com/nteract/hydrogen/issues/634#issuecomment-286465289).

Try rebuilding the package:

`apm rebuild ide-kotlin`

**Comment by kidanekal** [comment]
@fwcd  did `apm uninstall ide-kotlin` and then `apm install ide-kotlin` fixed the issue.
