### ISSUE TITLE
Can't seem to install this for Mac Atom

### ISSUE THREAD

**Issue by sangeetds** [fwcd/atom-ide-kotlin#3]
Whenever I try to install this on my Atom, the following error shows. Can I know what to do to resolve this?

```
 > tree-sitter-kotlin@0.2.3 install /private/var/folders/b3/2n0rtynx1t1ddxscphh70f880000gn/T/apm-install-dir-2020512-8845-srgph7.wvzmo/node_modules/ide-kotlin/node_modules/tree-sitter-kotlin
> node-gyp rebuild


No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/b3/2n0rtynx1t1ddxscphh70f880000gn/T/apm-install-dir-2020512-8845-srgph7.wvzmo/node_modules/ide-kotlin/node_modules/tree-sitter-kotlin
gyp ERR! node -v v10.20.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/b3/2n0rtynx1t1ddxscphh70f880000gn/T/apm-install-dir-2020512-8845-srgph7.wvzmo/package.json'
npm WARN apm-install-dir-2020512-8845-srgph7.wvzmo No description
npm WARN apm-install-dir-2020512-8845-srgph7.wvzmo No repository field.
npm WARN apm-install-dir-2020512-8845-srgph7.wvzmo No README data
npm WARN apm-install-dir-2020512-8845-srgph7.wvzmo No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter-kotlin@0.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-sitter-kotlin@0.2.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sangeetnarayan/.atom/.apm/_logs/2020-06-12T01_29_12_361Z-debug.log
```

**Comment by fwcd** [comment]
The Kotlin package uses a Tree-Sitter parser. Have you turned on "Use Tree Sitter Parsers" in your settings? If that doesn't resolve the issue, try installing the Xcode Command Line Tools (`xcode-select --install`).

**Comment by sangeetds** [comment]
Hi. Yes, I've turned it on and my Xcode command line tools are up-to-date. Is there anything else I need to ensure?

**Comment by sangeetds** [comment]
So I tried looking out in the web and it's actually an issue with the latest Mac update. Reinstalling the Xcode command line tools did the work for me.

**Comment by fwcd** [comment]
I assume that this issue is fixed and can be closed. Otherwise feel free to reopen.
